import Head from 'next/head'
import Navbar from '../components/Navbar'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <Navbar/>
        <div className='h-screen w-full'>
          <Image
            src="/../public/images/W&M.webp"
            layout='fill'
            objectFit='cover'
            alt="promo"
          />
        </div>
      </main>

      <footer className="flex items-center justify-center w-full text-center h-10 border-t-2 border-gray-700">
          <p>
            All Rights Reserved{' '}
            <span className=" font-bold">
              {/* <Image src="/vercel.svg" 
              alt="Vercel Logo" 
              width={72} 
              height={16}
            /> */}
              Mane & Woods
            </span>
          </p>
      </footer>
    </div>
  )
}
